function textwavebuttondownfcn(textWave, ~, guiNd)
    % TEXTWAVEBUTTONDOWNFCN Change the channel name
    %
    %
    
    %% Create an input dialog with the display name as the default name.
    % Get the current display name.
    displayName = get(textWave, 'String');

    parentPos = get(guiNd, 'Position');
    guiWidth = 254;
    guiHeight = 64;
    guiPos = [...
        parentPos(1) + parentPos(3)/2 - guiWidth/2, ...
        parentPos(2) + parentPos(4)/2 - guiHeight/2, ...
        guiWidth, ...
        guiHeight];
    
    waveToSet = regexp(get(textWave, 'Tag'), '\d{1,}', 'Match', 'Once');

    guiChannelName = figure(...
        'Color', 'k', ...
        'MenuBar', 'None', ...
        'Name', ['Enter channel ' num2str(waveToSet) ' name'], ...
        'NumberTitle', 'off', ...
        'Position', guiPos, ...
        'Resize', 'off', ...
        'Tag', 'displayName', ...
        'WindowStyle', 'Modal');
    
    % Create and edit box for display label.
    editDisplayName = uicontrol(...
        'Background', get(guiChannelName, 'Color'), ...
        'FontSize', 10, ...
        'Foreground', 'w', ...
        'Position', [20 20 150 24], ...
        'String', displayName, ...
        'Style', 'edit', ...
        'Tag', 'editDisplayName');
    
    % Create a reset button.
    xtndnderizerCData = getappdata(guiNd, 'xtndnderizerCData');
    uicontrol(...
        'Background', get(guiChannelName, 'Color'), ...
        'CData', xtndnderizerCData.Reset, ...
        'Callback', {@pushresetchannelnamecallback}, ...
        'FontSize', 10, ...
        'Foreground', 'w', ...
        'Position', [180 20 24 24], ...
        'Style', 'pushbutton', ...
        'Tag', 'pushResetChannelName');
    
    % Create an accept button.
    xtndnderizerCData = getappdata(guiNd, 'xtndnderizerCData');
    uicontrol(...
        'Background', get(guiChannelName, 'Color'), ...
        'CData', xtndnderizerCData.Accept, ...
        'Callback', {@pushnewchannelnamecallback}, ...
        'FontSize', 10, ...
        'Foreground', 'w', ...
        'Position', [210 20 24 24], ...
        'Style', 'pushbutton', ...
        'Tag', 'pushAcceptChannelName');

    %% Nested callback to reset the channel display name to the Metamorph wave name.
    function pushresetchannelnamecallback(varargin)
        % PUSHRESETCHANNELNAMECALLBACK
        %   
        %
        
        %%
        set([textWave, editDisplayName], 'String', get(textWave, 'UserData'))
    end % pushresetchannelnamecallback
    
    %% Nested callback to update the channel display name and close the figure.
    function pushnewchannelnamecallback(varargin)
        % PUSHNEWCHANNELNAMECALLBACK
        %   
        %
        
        %%
        set(textWave, 'String', get(editDisplayName, 'String'))
        close(guiChannelName)
    end % pushnewchannelnamecallback
end % textwavebuttondownfcn
