function protrusionAnalysisGUI()
%protrusionAnalysisGUI Creates the GUI, sets callback functions. R2015b
%   
% Kyle Marchuk, PhD
% Biological Imaging Development Center at UCSF
% Archived March 2017

% This is the user interface for protrusions analysis after the plane of
% interest has been isolated (Imaris). This uses .tif stacks. There are a
% few knobs to twist that need to be determined by the user to fit their
% data.
    %% Create the figure
    figWidth = 400;
    figHeight = 600;

    % Set the display position for the GUI
    displayPos = get(0,'MonitorPositions');
    
    if displayPos(1,2) > 0 
        figPos = [...
            (displayPos(1,3) - figWidth)/2,...
            (displayPos(1,4) - figHeight)/2,...
            figWidth,figHeight];
    else
        figPos = [...
            (displayPos(2,3) - figWidth)/2,...
            (displayPs(2,4) - figHeight)/2,...
            figWidth,figHeight];
    end % if
    
    guiPA = figure(...
        'Color',[0.1 0.1 0.44],...
        'Colormap',gray(256),...
        'MenuBar','None',...
        'Name','Protrusion Analysis',...
        'NumberTitle','Off',...
        'Position',figPos,...
        'Resize','Off',...
        'Tag','guiPA');
    
    %% Create a structure for the parameters and save it as appdata
    % This structure contains the defaults for the GUI. You can edit it
    % here to adapts the default GUI setting to match your preferences. As
    % users edit the parameters in the GUI, these values are updated. It
    % can also be used to store parameters that you do not want users to
    % edit
    
    structParameters = struct(...
        'inpathfile','Example.tif',...
        'inpathdir','C:...\Desktop',...
        'outpathdir','C:...\Desktop',...
        'currentFile','',...
        'newFolder','ProtrusionAnalysis',...
        'status','Status: Ready',...
        'medMult',4.5,...
        'timeRes',2.25,...
        'erodeExtent',4,...
        'shrinkExtent',3,...
        'area',13,...
        'sizeProtrusions',5);
    
    setappdata(guiPA,'structParameters',structParameters);
    
    %% Create the file path directory boxes
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',12,...
        'Foreground','w',...
        'Parent',guiPA,...
        'Position',[100 540 200 30],...
        'Style','text',...
        'String','Select File',...
        'Tag','textFileSelect')
    
    handles.displayInPathFile = uicontrol(...
        'Background',[0.53 0.80 0.98],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'HorizontalAlign','Left',...
        'Parent',guiPA,...
        'Position',[10 530 350 20],...
        'String',structParameters.inpathfile,...
        'Style','text',...
        'Tag','displayInPathFile');
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',12,...
        'Foreground','w',...
        'Parent',guiPA,...
        'Position',[100 490 200 30],...
        'Style','text',...
        'String','Save Directory',...
        'Tag','textSaveSelect')
    
    handles.displayOutPathDir = uicontrol(...
        'Background',[0.53 0.80 0.98],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'HorizontalAlign','Left',...
        'Parent',guiPA,...
        'Position',[10 480 350 20],...
        'String',structParameters.outpathdir,...
        'Style','text',...
        'Tag','displayInPathFile');
    
    uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Callback',{@pushInputFilecallback,guiPA,handles},...
        'FontSize',10,...
        'Parent',guiPA,...
        'Position',[370 530 20 20],...
        'String','...',...
        'Style','pushbutton',...
        'Tag','pushInPathFile',...
        'TooltipString','Find the .tif file');
    uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Callback',{@pushOutputFoldercallback,guiPA,handles},...
        'FontSize',10,...
        'Parent',guiPA,...
        'Position',[370 480 20 20],...
        'String','...',...
        'Style','pushbutton',...
        'Tag','pushOutPath',...
        'TooltipString','Find the save directory');
    
    %% Create new folder
    checkNewFolder = uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'FontSize',12,...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Parent',guiPA,...
        'Position',[125 445 200 20],...
        'String','Create New Folder?',...
        'Style','checkbox',...
        'Tag','checkNewFolder',...
        'TooltipString','Create a new folder within the output directory',...
        'Value',1);
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Parent',guiPA,...
        'Position',[100 420 200 20],...
        'Style','text',...
        'String','New Folder Name:',...
        'Tag','textFolderName');
    
    editNewFolder = mycontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',10,...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Parent',guiPA,...
        'Position',[125 395 150 20],...
        'String',structParameters.newFolder,...
        'Style','edit',...
        'Tag','editNewFolder');
    set(editNewFolder.Handle,'Callback',{@editNewFoldercallback,editNewFolder,guiPA})
    
    
    %% Create input boxes
    panelRunSettings = uipanel(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor','w',...
        'FontSize',12,...
        'BorderType','Line',...
        'HighlightColor',[0.53 0.80 0.98],...
        'Parent',guiPA,...
        'Position',[25 75 350 300]./[figPos(3) figPos(4) figPos(3) figPos(4)],...
        'Title','Sample Settings',...
        'TitlePosition','Centertop',...
        'Tag','panelRun',...
        'Units','Pixels');
    uistack(panelRunSettings,'bottom')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[0.53 0.80 0.98],...
        'Parent',panelRunSettings,...
        'Position',[10 250 150 20],...
        'Style','text',...
        'String','Threshold Method',...
        'Tag','textTheshMeth')
    popThresholdMenu = uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelRunSettings,...
        'Position',[35 225 100 20],...
        'String',{'median','im2bw'},...
        'Value',1,...
        'Style','popupmenu',...
        'Tag','popThresholdMenu');
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[0.53 0.80 0.98],...
        'Parent',panelRunSettings,...
        'Position',[175 250 150 20],...
        'Style','text',...
        'String','Median Multiplier',...
        'Tag','textMedMult')
    
    editMedianMultiplier = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelRunSettings,...
        'Position',[225 225 50 20],...
        'Style','edit',...
        'String',structParameters.medMult,...
        'Tag','editMedianMultiplier',...
        'TooltipString','Enter Multiplier');
    set(editMedianMultiplier.Handle,'Callback',{@editMedianMultipliercallback,editMedianMultiplier,guiPA})
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[0.53 0.80 0.98],...
        'Parent',panelRunSettings,...
        'Position',[10 185 150 20],...
        'Style','text',...
        'String','Center of Mass',...
        'Tag','textCoM')
    
    checkErode = uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelRunSettings,...
        'Position',[35 165 100 20],...
        'String','Erode CoM?',...
        'Style','checkbox',...
        'Tag','checkErode',...
        'TooltipString','Erode threshold for CoM calculation',...
        'Value',1);
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[0.53 0.80 0.98],...
        'Parent',panelRunSettings,...
        'Position',[175 185 150 20],...
        'Style','text',...
        'String','Erode Extent',...
        'Tag','textErodeExtent')
    
    editErodeExtent = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelRunSettings,...
        'Position',[225 165 50 20],...
        'Style','edit',...
        'String',structParameters.erodeExtent,...
        'Tag','editMedianMultiplier',...
        'TooltipString','Size of Erode Tool');
    set(editErodeExtent.Handle,'Callback',{@editErodeExtentcallback,editErodeExtent,guiPA})

     uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[0.53 0.80 0.98],...
        'Parent',panelRunSettings,...
        'Position',[10 75 150 20],...
        'Style','text',...
        'String','Protrusion Size (pix)',...
        'Tag','textProSize') 
    
    editProtrusionSize = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelRunSettings,...
        'Position',[55 50 50 20],...
        'Style','edit',...
        'String',structParameters.sizeProtrusions,...
        'Tag','editProtrusionSize',...
        'TooltipString','Enter square protrusion size');
    set(editProtrusionSize.Handle,'Callback',{@editProtrusionSizecallback,editProtrusionSize,guiPA})
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'Foreground',[0.53 0.80 0.98],...
        'Parent',panelRunSettings,...
        'Position',[175 75 150 20],...
        'Style','text',...
        'String','Time Resolution (s)',...
        'Tag','textMedMult')
    
    editTimeResolution = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelRunSettings,...
        'Position',[225 50 50 20],...
        'Style','edit',...
        'String',structParameters.timeRes,...
        'Tag','editTimeResolution',...
        'TooltipString','Enter Seconds per Frame');
    set(editTimeResolution.Handle,'Callback',{@editTimeResolutioncallback,editTimeResolution,guiPA})
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'Fontsize',11,...
        'Foreground',[ 0.53 0.80 0.98],...
        'Parent',panelRunSettings,...
        'Position',[8 135 150 20],...
        'Style','text',...
        'String','Shrink Extent',...
        'Tag','textShrinkExtent')
    
    editShrinkExtent = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelRunSettings,...
        'Position',[55  115 50 20],...
        'Style','edit',...
        'String',structParameters.shrinkExtent,...
        'Tag','editShrinkExtent',...
        'TooltipString','Extent to Shrink the Mask');
    set(editShrinkExtent.Handle,'Callback',{@editShrinkExtentcallback,editShrinkExtent,guiPA})
    
    handles.textStatus = uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'Foreground','w',...
        'FontSize',9,...
        'Parent',panelRunSettings,...
        'Position',[90 10 150 20],...
        'Style','text',...
        'String',structParameters.status,...
        'Tag','textStatus');
    
    
    %% Create final run/stop commands
    handles.pushStop = uicontrol(...
        'BackgroundColor',[0.53 0.80 0.98],...
        'ForegroundColor',[0.7 0.13 0.13],...
        'Callback',{@pushStopcallback,handles},...
        'String','STOP!',...
        'FontSize',14,...
        'Style','pushbutton',...
        'Parent',guiPA,...
        'Value',1,...
        'Position',[205 10 80 40],...
        'Tag','pushStop',...
        'TooltipString','Quit Program');
    
    uicontrol(...
        'BackgroundColor',[0.53 0.80 0.98],...
        'ForegroundColor',[0.1 0.1 0.44],...
        'Callback',{@pushRuncallback,checkNewFolder,popThresholdMenu,checkErode,guiPA,handles},...
        'FontSize',14,...
        'Parent',guiPA,...
        'Position',[115 10 80 40],...
        'String','RUN!',...
        'Style','pushbutton',...
        'Tag','pushRun',...
        'TooltipString','Go!');
    

end

